version: '3.8'
services:

  postgres:
    image: postgres:16-alpine
    container_name: my-spring-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Seoul
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # PostgreSQL 공식 이미지의 초기화 경로는 /docker-entrypoint-initdb.d 입니다.
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    restart: always

  redis:
    image: redis:7.2.5-alpine
    container_name: my-spring-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    restart: always

# 데이터 영속성을 위한 볼륨 정의
volumes:
  mysql-data: