jwt:
  # JWT ??? ?: .env ???? ?? ??? ??? ?????.
  secret: ${JWT_SECRET_KEY}
  # JWT ?? ?? ?? (? ??): .env ???? ?? ??? ??? ?????.
  expiration: ${JWT_EXPIRATION_SECONDS}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION_SECONDS}

spring:
  # ??? ?? (DataSource) ??
  datasource:
    # JDBC ???? ??? ??
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true

  mail:
    host: smtp.naver.com # 네이버 SMTP 서버 주소
    port: 465
    username: ${MAIL_EMAIL} # 본인의 네이버 이메일 주소
    password: ${MAIL_PASSWORD} # 생성한 애플리케이션 비밀번호
    properties:
      mail:
        smtp:
          auth: true # 인증 사용
          # 💡 수정: SSL 대신 TLS 활성화
          ssl:
            enable: true # SSL 비활성화
            trust: smtp.naver.com


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

app:
  base-url: http://localhost:8080
