jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION_SECONDS}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION_SECONDS}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true

  mail:
    host: smtp.naver.com # 네이버 SMTP 서버 주소
    port: 465
    username: ${MAIL_EMAIL} # 본인의 네이버 이메일 주소
    password: ${MAIL_PASSWORD} # 생성한 애플리케이션 비밀번호
    properties:
      mail:
        smtp:
          auth: true # 인증 사용
          # 💡 수정: SSL 대신 TLS 활성화
          ssl:
            enable: true # SSL 비활성화
            trust: smtp.naver.com
          connection timeout: 10000
          timeout: 10000


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

app:
  base-url: https://lineup-maker-api.onrender.com
